version: '3.4'

networks:
  skynet:
    driver: bridge

services:
  # pdfkit:
  #   hostname: pdfkit
  #   container_name: pdfkit
  #   image: pspdfkit/processor
  #   ports:
  #     - '5000:5000'
  #   networks:
  #     - skynet
  puppeteer:
    hostname: puppeteer
    # image: node:12.16.3-slim
    build:
      context: .
      dockerfile: ./Dockerfile
      shm_size: '2gb'
    shm_size: '2gb'
    command: ["yarn", "docker:start"]
    ports:
      - "4200:4200"
    volumes:
      - ./puppeteer:/home/pptruser/app
      - /home/pptruser/app/node_modules
    networks:
      - skynet
